export const selectAllPokemon = (state) => state.allPokemonData;
export const selectPosition = (state) => state.position
export const selectEncounter = (state) => state.encounter
export const selectCollisionCoord = (state) => state.collisionCoord
export const selectGrassCoord = (state) => state.grassCoord
export const selectPokemonEncounter = (state) => state.pokemonEncounter
export const selectInventory = (state) => state.inventory
export const selectBagWindow = (state) => state.bagWindow
export const selectSystemMessage = (state) => state.systemMessage
export const selectCurrentItemIndex  = (state) => state.currentItemIndex
export const selectCurrentPokeball = (state) => state.currentPokeball
export const selectCurrentBait = (state) => state.currentBait
export const selectCurrentInterfaceIndex =(state) => state.currentInterfaceIndex
export const selectLoading = (state) => state.loading
export const selectUseBait = (state) => state.useBait
export const selectPokemonList = (state) => state.pokemonList
export const selectThrown = (state) => state.thrown
export const selectStart = (state) => state.start
export const selectScore = (state) => state.score
export const selectMapItemList = (state) => state.mapItemList
export const selectItemCoord = (state) => state.itemCoord
